### PR TITLE
token encryptor decryptor lib

### PR DESCRIPTION
**Pull request by noam-almog**
token encryption/decryption lib, to be used for jwt token

### CODE REVIEW

**Comment by OriHoch** [comment]
thanks @noam-almog - it looks like a very useful package, why not publish it as a module on npm?

regarding spark - I'm not sure how it will be used, this PR contains only the library, without actually using it in Spark.

**Comment by OriHoch** [comment]
@noam-almog if you could write how this library would be used in regards to the spark SSO spec, that would be very useful - https://github.com/Midburn/Spark/blob/master/docs/usage/SSO.md

**Comment by noam-almog** [comment]
@OriHoch this is not complete yet, it's just the first part.
the integration modules will be written (hopefully) today.
btw, do we have a local npm repo ?

**Comment by OriHoch** [comment]
cool, @noam-almog please prefix the pull request title with [WIP] so we know not to review and merge it

we don't have a local npm repo as far as I know

**Comment by noam-almog** [comment]
@OriHoch actually i prefer to merge it now, i'll create newer pr that will use it
i don't like gigantic PRs, it makes it hard to understand what to look it.
WDYT ?

**Comment by OriHoch** [comment]
no problem, given that -
1. you are going to use it
2. it does not affect any existing processes (as it's not used yet..)

I have no objection to you merging it

**Review by OriHoch — APPROVED** [review]

**Comment by OriHoch** [comment]
@noam-almog  - oh, actually, builds are failing - so please make sure you fix them before merging..

**Comment by OriHoch** [comment]
oops, please fix the build ASAP - it will prevent other people from working...

**Comment by noam-almog** [comment]
@OriHoch when i coded it all tests passed

**Comment by OriHoch** [comment]
ok, might be some fluke on Travis.. please have a look at travis build logs

**Pull request merged**
