### PR TITLE
Change license to Apache 2.0

### PR DESCRIPTION
**Pull request by kaplanlior**
Aligning the project license after discussion on Slack.

I'll ask every contributor to accept this license change, and will manually verify everyone has accepted it before merging this pull request.

### CODE REVIEW

**Comment by kaplanlior** [comment]
Tagging people to get their approval for license change, ordered by number of commits:

@OriHoch @guywarburg @ripper234 @roy-zahor @eyalliebermann @LeonFedotov @asihud @ArtyomKa @nitay-neeman @amotenko @rootux @shayerov @noamr @alondanoch @yules @sh0oki @mickeyil @BBBmonkey

**Comment by ripper234** [comment]
I approve

**Comment by amotenko** [comment]
should we wait for everyone to approve?

**Comment by LeonFedotov** [comment]
maybe just outline the points for the decision in the issue and get on with the change.

**Comment by kaplanlior** [comment]
For formality sake, we'll wait for everyone.

**Review by ArtyomKa — APPROVED** [review]

**Comment by roy-zahor** [comment]
@kaplanlior I'm not familiar with licensing issues, so some basic questions:
What's our current license? 
Why choosing Apache 2.0?

**Comment by ripper234** [comment]
FYI our current license is nothing, which is bad for the reusability of the project by other devs.

Here is a [short presentation](https://docs.google.com/presentation/d/1GMAiyDT14XlSKXtTiDULqTgceEFzo6H4bM1NVW593Ng/edit#slide=id.g20b2c4d754_0_668) I made a while ago about choosing a license. I also recommended Apache, reasoning is inside the presentation / verbally.

**Pull request closed without merging**
