### PR TITLE
Add link to /dev portal to server startup log

### PR DESCRIPTION
**Pull request by ripper234**

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]
very cool! I like it

**Comment by roy-zahor** [comment]
https://github.com/Midburn/Spark/pull/338 Gives a more comprehensive solution by adding the link to the login page (in debug env) and to the footer.
But, we can still merge this PR (after resolving conflicts). I would suggest that the new link will only appear if the system env is development:  if (app.get('env') === 'development') { ... }

**Comment by ripper234** [comment]
Is that page even functional? Last time I checked (a few months ago) its main functionality (login) was broken.
Not sure whether that page currently has value or not.

**Comment by roy-zahor** [comment]
@ripper234  Of course it is working, and people are using it.

**Pull request closed without merging**
