### PR TITLE
presale input control date

### LINKED ISSUE #476: Integrate an input control for time-date on the camps form
### Overview of the problem
On all forms, we do not have input control of type Date Time type. 

### Steps to Reproduce
- [x] On Camps /views/pages/camps/index_admin.jade we need to add this control on a form. 
- [ ] Add the javascript that create this (unless we already having class that implemented the date time control

### PR DESCRIPTION
**Pull request by yaniv-peretz**
### on the http://localhost:3000/he/camps-admin page 
presale input column would be enabled as long as current date is still before event presale tickets start date

--------------
note: constants.PRESALE_TICKETS_START_DATE should come form the actual event (not hard coded)
#### please note to merge and squash together!
closes #476

### CODE REVIEW

**Review by amotenko — CHANGES_REQUESTED** [review]
My only question is about end date,
do we also check against it as well as we do for start date?

**Comment by yaniv-peretz** [comment]
Don't think so,
Q: is there another time in the future where we should unlocked to pre-sale-allowance after pre-sale-start-date?

As I understand it, at pre-sale-start-date we need to lock the pre-sale-allowance, then
form pre-sale-start-date to pre-sale-**end-**date it is locked, then
from pre-sale-end-date to infinity it is locked.

if so, this is currently how it is setup.

**Review by guyzohar1 — CHANGES_REQUESTED** [review]
the original request is to remove the constant:
//TODO once the event table will be updated with presale ticket time, this needs to be replace
        if (isAdmin === false) {
            var currentTime = new Date();
            var start=new Date(constants.PRESALE_TICKETS_START_DATE);
            var end=new Date(constants.PRESALE_TICKETS_END_DATE);
            if (currentTime.getTime() < start.getTime() || currentTime.getTime() > end.getTime()) {
                throw new Error("PreSale Tickes selection is currently closed");
            }
        }

and use the event start/end date from the events table

**Comment by yaniv-peretz** [comment]
@guyzohar1 
We need to farther discuss of to test it on the UI on Monday,
for the time, i've updated another commit (dd9ba32729da61cadf669f0908a96ff7e3fb7349), with dates coming form the events table based on constant current event _id (until we pull current event ID from the session).

**Comment by yaniv-peretz** [comment]
moved to a new PR #559

**Pull request closed without merging**
