### PR TITLE
Added support for running tests on Travis-CI

### PR DESCRIPTION
**Pull request by OriHoch**
Travis-CI is free for open source projects

https://travis-ci.org/OriHoch/Spark/builds/190556286

tests are failing but not because of Travis-CI..

### CODE REVIEW

**Comment by OriHoch** [comment]
follow-up issue: #9

**Comment by netanelben** [comment]
great contribution, CI is needed from day-1.
need all to review

**Comment by amotenko** [comment]
This should hopefully work with our docker image. Once we have a staging server with a working docker image this should be tested against it and merged.

**Comment by ripper234** [comment]
ACK, Great work. 

1. Knex should be used for migrations instead of plain SQL as per #4. (current .sh calls them). The `/sql` folder is deleted in another #18 I believe, let's update this PR to reflect that.

2. Please no .sh files, I think it's better to put the logic there into the package.json file directly (let's use that as a build system). See [Introduction to Using NPM as a Build Tool](https://medium.com/@dabit3/introduction-to-using-npm-as-a-build-tool-b41076f488b0#.jej48e7ie).

(Item 2 above is not a blocker, I ACK this PR, if you don't do Item 2 please copy-paste the text above into a new issue)

**Review by ripper234 — APPROVED** [review]
ACK, Great work. 

1. Knex should be used for migrations instead of plain SQL as per #4. (current .sh calls them). The `/sql` folder is deleted in another #18 I believe, let's update this PR to reflect that.

2. Please no .sh files, I think it's better to put the logic there into the package.json file directly (let's use that as a build system). See [Introduction to Using NPM as a Build Tool](https://medium.com/@dabit3/introduction-to-using-npm-as-a-build-tool-b41076f488b0#.jej48e7ie).

(Item 2 above is not a blocker, I ACK this PR, if you don't do Item 2 please copy-paste the text above into a new issue)

**Comment by OriHoch** [comment]
thanks @ripper234  - I will update according to your comments and merge

**Comment by OriHoch** [comment]
There are some conflicts, I'll open a new PR

**Pull request closed without merging**
