### PR TITLE
fix bug with plus sign in email address which prevents login to spark

### LINKED ISSUE #575: Login with an email address that has the '+' sign doesn't work
bug

no

### Overview of the problem
My Midburn profile is talbarda88+midburn@gmail.com but I can't login with it, and I can login only with _talbarda88midburn@gmail.com_ (pay attention the second address doesn't have the '+' sign).
This could have other consequences such sending me an email to the wrong email address.

### PR DESCRIPTION
**Pull request by OriHoch**
fixes #575 

(this bug is caused by [this bug in profiles](https://github.com/OriHoch/midburn-profiles-drupal/issues/1))

### CODE REVIEW

**Comment by OriHoch** [comment]
there are 8 such users in the spark production DB - all should be fixed (tested with a user I created)

**Comment by amotenko** [comment]
So Drupal simply ignores the plus signs?
When you say you fixed the users do you mean you removed the pluses from the emails?

**Comment by OriHoch** [comment]
the fix is in the PR - drupal looks for these users without the plus sign, so I adjusted our code to match..

haven't changed anything to any users, it works

**Comment by amotenko** [comment]
Sababa please only comment why we do that and we'll have to remember to revert that line when we move profiles out from Drupal

**Comment by OriHoch** [comment]
@amotenko the comment above my change links to this PR, any other changes needed?

**Comment by amotenko** [comment]
@OriHoch , it's cool

**Pull request merged**
