### PR TITLE
Add 1st end-to-end sanity test

### PR DESCRIPTION
**Pull request by ripper234**

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]
:+1:

**Comment by ripper234** [comment]
@OriHoch do you have merge permissions? I think if one person reviews & approves a PR, it should be immediately merged, and core team members should have the permissions to do that.

**Comment by amotenko** [comment]
@ripper234 I don't think it's possible to merge right now seeing as there are conflicts

**Comment by OriHoch** [comment]
@ripper234 - I would be more comfortable merging stuff after approval from maintainer or based in some guidelines about when we should merge / what's the process..

**Comment by ripper234** [comment]
I actually see I have commit access now and I can merge them.

@amotenko @asihud what's the process? Should I merge changes myself (after they have been reviewed & approved)

**Comment by amotenko** [comment]
If it has been reviewed and you feel confident in it, than sure, go ahead

**Comment by OriHoch** [comment]
@ripper234 this pull request caused some problems on deployment and testing
I can see now it contains some configuration changes which require syncing with deployment / production servers etc..

please re-open this PR and will need to review again

@ArtyomKa @amotenko

**Comment by ripper234** [comment]
Thanks, will do.

**Pull request merged**
