### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by ripper234**
This PR adds:

- `npm lint` to run the linter (based on [standard.js](http://standardjs.com/)
- `npm test` now depends on lint as a precondition
- fixes the code issues so the lint is green
- (some styling rules are turned off, because fixing them would be too big for this PR and I want to keep the lint green)

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]

**Comment by ripper234** [comment]
@natekonimbo & @amotenko , I'm waiting for your review.

**Comment by ripper234** [comment]
@natekonimbo / @amotenko this PR touches many files, it's important to merge while there are no merge conflicts. I checked it again now and everything passes, would be great if you can merge it this week.

**Comment by netanelben** [comment]
Agree!

I will review this one tonight!

**Comment by netanelben** [comment]
@ripper234 Can't test this change -- its not in a branch

**Comment by ripper234** [comment]
What do you mean? It's in ripper234:add-linter?

image

**Review by natekonimbo — APPROVED** [review]
:ok:

**Pull request merged**
