### PR TITLE
Api refactor feb 2018

### PR DESCRIPTION
**Pull request by NitayRabi**
#### API restructure
- API is now structured under - 
- routers - separate `express` routers with prefix, paths, middlewares etc...
- controllers - all `control` functions (function which accepts (req, res, next)).
- services - separate business logic used across different controllers (db interactions).
- single point of entry - the api uses a single api main router which initializes all other routers with
correct prefixs. 

### Testing Done
- I Navigated and debugged the system, didn't see any errors or 404's (I NEED WITH UI EXPERIENCE TO SEE NOTHING IS BROKEN)

### Comments 
**I Kept most functions internal logic beside fixing lint errors and merging similar functions**
**I Kept all original api folder for time being**
**The way the app starts the routers will be changed in stage 2 of refactor**
**I Haven't refactored  main_routes.js which holds middlewares (e.g breadcrumbs), views and api's - will be changed in a later stage**

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]
looks great!

**Comment by OriHoch** [comment]
look like only 1 test is failing.. pretty good for such a refactor ..
```
  1) Main routes returns 404 MOOP! on everything else:
     Error: expected body 'Forbidden' to match /<[Hh]1>MOOP!<\/[Hh]1>/
      at error (node_modules/supertest/lib/test.js:299:13)
      at Test._assertBody (node_modules/supertest/lib/test.js:213:16)
      at Test._assertFunction (node_modules/supertest/lib/test.js:281:11)
      at Test.assert (node_modules/supertest/lib/test.js:171:18)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1655:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by NitayRabi** [comment]
@OriHoch - Yeah i saw that test fail yesterday and i'll probably get around to look at it this afternoon 👍

**Comment by amotenko** [comment]
Looks amazing. Would love if we could go over the main points tomorrow together.

**Comment by yaniv-peretz** [comment]
looks impresive :+1: @NitayRabi 

Q: what is the purpose of naming the folder '/api-18/' ?
Form what I understand this recommended mostly when developing external api (api for other external developer to integrate into such as google maps api act...). if these routes are our internal app routes, then I don't see the benefit maintaining correct api-$version with sequential commits.

**Comment by yaniv-peretz** [comment]
Very nice split for the controllers & routers, :+1: :+1: 
small suggestion though...

Frequent usage of:  
`router.route('path').METHOD(function())`.
but in most cases a shorter & more direct approach will suffice.
 `router.METHOD('path', function())`

according to express Api: "Use router.route() to avoid duplicate route naming and thus typing errors."
meaning that it is used for when there is a shared api path. looking at the routers, this is not the case.

example for (typical REST api - unfortunately not where we at right now ):
```
router.route('/users/:user_id')
.all(function(req, res, next) {
  // runs for all HTTP verbs first
  // think of it as route specific middleware!
  next();
})
.get(function(req, res, next) {
  res.json(req.user);
})
.put(function(req, res, next) {
  // just an example of maybe updating the user
  req.user.name = req.params.name;
  // save user ... etc
  res.json(req.user);
})
.post(function(req, res, next) {
  next(new Error('not implemented'));
})
.delete(function(req, res, next) {
  next(new Error('not implemented'));
});
```
http://expressjs.com/en/4x/api.html#router.route
http://expressjs.com/en/4x/api.html#router.METHOD

**Comment by yaniv-peretz** [comment]
Last thing: wrapping each router as a class, with it's own logic.
could you elaborate?

I'm not sure OOP approach, is common \ beneficial for express routes. 
both MDN & express docs are functionally declaring routes.

beside being uncommon, it is also introducing new middleware flow to express where route specific middleware isn't at the top.
example, route specific middleware go on top, followed by all routes. 

```
// middleware that is specific to this router
router.use(function timeLog (req, res, next) {
  do something
  next()
})
```

OOP is great when we might need to create many new instances of the same block, (many new Obj()), but for routes I'm not sure it is the case.

Express docs: http://expressjs.com/en/guide/routing.html#express-router
MDN docs: https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#Create_the_catalog_route_module

**Comment by NitayRabi** [comment]
@Yanipo5  - Regarding your questions - 
### api-18.
 I named it temporary in order to keep a reference to routing order and functions as they were before the refactor until we validate everything works.

### Usage of `route`.
every API needs to strive towards having less paths and more diverse methods on the same path, and even if we're not there - i wrote the paths ready just to add another method instead of an entire route. and in my experience, due to the nature of `express` docs - people tend to only know the `router[method]()` way - thus causing too many paths. keeping it in `route` form is more intuitive IMO for adding more methods.

### Why OOP - 
- In the end what we do is write modules. and you choose the structure of the output of a module. I find `class` to be most suitable because you can decide on a `transient` vs `singleton`, able to `extend` functionality (again, we're not there but we can strive for a more generic `extending` approach).
If you want to see what i mean you can see https://github.com/NitayRabi/sampleexpress 
- Flow control - I like to choose what happens, not on a line by line basis (as exampled in docs), as for your middleware example - this is what i do in the constructor - I choose when to init routes without middleware, then activate router level middlewares and then activate post-middleware routes. and it's all a lot more readable, and controllable process (which is important in a volunteers based system, and debugging).
- Design pattern - the express docs and MDN explain syntax and general approach to a certain library (express), and the OOP used is here more of a design pattern of routers-controllers-services using express.

**Comment by yaniv-peretz** [comment]
Ok for 1 & 2,
not sure I see the benefit for 3 (OOP) of deviating from a "standard"\common approach,
particularly in order to keep Spark Dev. learning curve to a minimum.
but It's a group/your decision. (end of discussion for me).

**Review by yaniv-peretz — APPROVED** [review]
not sold on the OOP design for routes.

**Comment by OriHoch** [comment]
@NitayRabi I enabled continuous deployment of this branch to sparktesting environment at https://spark.testing.midburn.org/

There is an error with the migrtaions - 

```
ori@ori-ThinkPad-T560:~/midburn-k8s$ midbarrn-midbarrn-sparktesting$ kubectl logs spark-86866cb874-krrv8 -c migrations
Spark: knexfile.js - IN
Spark config: package.json version: 2.10.24
Spark config: .env file was not found, using default config.
Spark config: Using MySQL database sparkdb / spark
Spark: knexfile.js - OUT
Using environment: development
Error: The migration directory is corrupt, the following files are missing: 20180308221834_ticket_barcode_nullable.js
    at validateMigrationList (/home/spark/node_modules/knex/lib/migrate/index.js:536:11)
    at PassThroughHandlerContext.finallyHandler (/home/spark/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/home/spark/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/spark/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/spark/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/spark/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/spark/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/spark/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/spark/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/spark/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/spark/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/spark/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/spark/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/spark/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/spark/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/spark/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by NitayRabi** [comment]
Merged DGS allocation PR.
Merged disabling editing of camps PR
Merged Suppliers PR

**Comment by NitayRabi** [comment]
@OriHoch - 
Something with deploying to testing has gone wrong, how can i know what is it?
image

**Comment by OriHoch** [comment]
@NitayRabi if you click on the failing job you can see the full log

there is too much logs there, but the relevant error is [here](https://travis-ci.org/Midburn/spark/jobs/357832266#L553) - 
```
Error from server (NotFound): deployments.extensions "spark-drupal-sync" not found
failed to patch spark-drupal-sync deployment
```

So, there is a problem with drupal-sync, but other then that, looks like spark is deployed

this is the latest pod, looks like it's running the image for the latest commit in this PR https://console.cloud.google.com/kubernetes/pod/us-central1-a/midbarrn/sparktesting/spark-78999d6d58-mxcqb?project=midbarrn&tab=details&duration=PT1H&container_summary_list_tablesize=10

image

**Pull request merged**
