### PR TITLE
Migrate payment ajax from request to superagent

### PR DESCRIPTION
**Pull request by LeonFedotov**
Hello, this pr includes #197 and adds payment refactor, this needs to be tested and validated by hand to be 100% implementation is expected behavior...

### CODE REVIEW

**Comment by LeonFedotov** [comment]
@roy-zahor @ripper234 maybe you guys can take a look.

**Comment by ripper234** [comment]
I don't have commit/review access, @amotenko ?

FYI I did review the change and it looks good to me.

**Comment by netanelben** [comment]
@ripper234 Fixed.

**Review by ripper234 — APPROVED** [review]
LGTM

**Comment by amotenko** [comment]
@LeonFedotov what kind of manual tests are required?

**Comment by LeonFedotov** [comment]
@amotenko I mean, run it once see if it works, im not sure how you test the payment part w/o actually paying, they probably have some sandbox "state" you need to configure your account to or different url endpoint of something

**Pull request merged**
