### PR TITLE
Fixes #538 

### LINKED ISSUE #538: bug- as a admin, i can't enter and view an art installation
As a admin, when i click on ניהול מיצבים and than try to view the camp details i'm getting an error page
screenshot 2018-01-05 at 17 42 59
I suppose to be able to see the art intallation details.

### PR DESCRIPTION
**Pull request by ArtyomKa**
### Proposed solution

removed the camp prototype constraint from the query
### Tradeoffs

Not sure why there was a constraint in the first place

### CODE REVIEW

**Comment by amotenko** [comment]
if camps === art I don't see a reason why. Let's hear what @asihud has to say

**Comment by amotenko** [comment]
Actually let's get the fix out as there are QA engineers waiting @ArtyomKa

**Review by amotenko — APPROVED** [review]

**Comment by ArtyomKa** [comment]
I can merge... but i don't even know what the correct behavior is (that is besides not to crash).
right now, the system navigates to _camp_ details. there is no indication that it is an _art_installation_ we are viewing...

**Comment by amotenko** [comment]
https://github.com/Midburn/spark/issues/538

**Pull request merged**
