### PR TITLE
NPO enhancments

### PR DESCRIPTION
**Pull request by roy-zahor**
### Proposed solution
This PR includes:
1. NPO features:
    a. New member admin form.
    b. Improvements to joining process.
2. Tons of bugfixes in NPO module and in the core infrastructure.
3. Infrastructure updates to address several problems raised lately on production server:
    a. Adding global query error handler to knex to catch query errors and log them.
    b. Upgrading config file with logic that will assure loading the environment variables, even when running knex migrations.
    c. Changes in .travis.yml file: Removing duplicate bower install and adding export to sqlite3 DB.
    d. Fixing all DB migrations so they will work with MySql.
    e. knex upgrade to v0.12.9 to get better DB error messages.
    f. Adding Spark version to footer and adding more debug info to the login page.

### Tradeoffs
None. See known issues below.

### Testing Done
NPO - Manual tests. iCredit was not tested.
Core - Running all automatic test. All passed.

### Known issues
1. In NPO module - The code assumes that all payments are for the current year, but this is incorrect. It should check since the year the member joined the NPO.
2. No known issues in core modules.
3. **Migrations and test of volunteers module have been disabled, since they are not passing while running on MySql and fail on npm test. This will need to be resolved on future integration with this module.**

### CODE REVIEW

**Review by OriHoch — APPROVED** [review]
looks good to me

how would we deploy this change? considering that we have existing data in DB, and some migrations which you edited already ran on production, so won't run again (and even if they did, the tables already exist)

**Comment by roy-zahor** [comment]
Ori, you are perfectly right about the migrations. I guess we should take a schema dump from the production server and make sure that running all migrations on an empty DB produces the same schema as in the production server. I didn't make it yet, because I've seen other PRs that address this.

**Comment by OriHoch** [comment]
better to do everything in this PR

do you want me to send you the productio db schema?

also, worth to have travis use mysql, was mostly done in my pr, i can merge that into this pr if you want

**Comment by OriHoch** [comment]
changed travis to use mysql in this PR to your branch: https://github.com/roy-zahor/Spark/pull/1
[build is passing](https://travis-ci.org/OriHoch/Spark/builds/225951799)
@roy-zahor feel free to merge to this PR

**Comment by roy-zahor** [comment]
@OriHoch Please send me the production DB schema. Thanks

**Comment by OriHoch** [comment]
[spark-production-schema-2017-04-26.sql.txt](https://github.com/Midburn/Spark/files/958413/spark-production-schema-2017-04-26.sql.txt)

this is how I got it:
```
$ ssh midburn-spark-production-i-08a916e0d17210235
ubuntu@ip-172-31-32-142:~$ . /opt/spark/.env
ubuntu@ip-172-31-32-142:~$ mysqldump -d -h $SPARK_DB_HOSTNAME -u $SPARK_DB_USER -p$SPARK_DB_PASSWORD $SPARK_DB_DBNAME
```

**Comment by OriHoch** [comment]
@roy-zahor you are supposed to update the release notes on every merge
see https://github.com/Midburn/Spark/blob/master/docs/development/releases-and-deployment.md

in this case it's important to add deoloyment notes that clearly state that the release cannot be deployed due to db mismatch..

**Comment by OriHoch** [comment]
I also think that the deployment to test failed for this merge

**Comment by OriHoch** [comment]
yes, build failed
https://travis-ci.org/Midburn/Spark/builds/226036114

```bash
Spark: knexfile.js - IN
Spark config: package.json version: 2.2.2
Spark config: Loading .env file...
Spark config: Using MySQL database localhost
Spark: knexfile.js - OUT
Using environment: development
Error: The migration directory is corrupt, the following files are missing: 20170303180503_volunteers.js, 20170308194518_rename_volunteers_table.js
    at validateMigrationList (/opt/spark/new/node_modules/knex/lib/migrate/index.js:501:11)
    at PassThroughHandlerContext.finallyHandler (/opt/spark/new/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/opt/spark/new/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/spark/new/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/spark/new/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/spark/new/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/spark/new/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/opt/spark/new/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/opt/spark/new/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/opt/spark/new/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/opt/spark/new/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/opt/spark/new/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/spark/new/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/spark/new/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/spark/new/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/spark/new/node_modules/bluebird/js/release/async.js:17:14)
ERROR
error in deploy stage
ERROR!
The command ".travis/deploy.sh" exited with 1.
```

**Comment by roy-zahor** [comment]
@OriHoch I will fix everything soon.

**Comment by roy-zahor** [comment]
Details about the problem and the fix on https://github.com/Midburn/Spark/pull/355

**Comment by OriHoch** [comment]
@roy-zahor don't want to be a נודניק but.. what about updating the release notes?

It's very important to update directly after merge, especially because we have lot's of different people working on the project and it's hard to track the changes..

if you think we should not update release notes after merge and you have some other flow you want to use, let us know, but we should all use the same workflow

**Comment by OriHoch** [comment]
BTW, updating the release notes is as simple as copy-pasting the title of the pull requst to the notes
(of course, better to write some details, but that's a bonus)

**Comment by roy-zahor** [comment]
@OriHoch I wan't familiar with this release procedure, sorry. I'm doing it now, and from now on I'll stick to it. Thanks

**Pull request merged**
