### PR TITLE
Make running tests work locally on Windows (was broken)

### PR DESCRIPTION
**Pull request by ripper234**
Running `npm test` was broken on Windows due to usage of `rm -rf` and `export`.
Switched to using npm packages `rimraf` and `cross_env`.

### CODE REVIEW

**Review by LeonFedotov — APPROVED** [review]
looks goot

**Comment by ripper234** [comment]
@LeonFedotov can you merge this? I have no write access.

**Comment by LeonFedotov** [comment]
@ripper234 I don't have merge permission.

**Comment by ripper234** [comment]
@amotenko ?

**Pull request merged**
