### PR TITLE
moved sensitive configurations to opsworks.js

### PR DESCRIPTION
**Pull request by OriHoch**
should ask GitHub support to remove all history for this file..

### CODE REVIEW

**Comment by ripper234** [comment]
@OriHoch 

This is how to remove sensitive files from github history, no need to contact support.

https://help.github.com/articles/remove-sensitive-data/

However, the files were already committed (so you can't be sure nobody copied the data), and besides it's a good chance to do it - I propose we take this chance to change any secret values. It's a good practice to change these sometimes, I bet it's been awhile since these were updated.

**Comment by ripper234** [comment]
@OriHoch I granted you commit access, you can test & merge the PR.

**Comment by OriHoch** [comment]
Agreed.. best to change the secrets

**Comment by OriHoch** [comment]
About the opsworks file - I'm not familiar with it, I assume you have a way to update it on production?

**Comment by ripper234** [comment]
Me neither...

I'm posting to Slack.

**Pull request merged**
