### PR TITLE
hot reload added

### PR DESCRIPTION
**Pull request by yaniv-peretz**
Adding hot reload via CLI:
`npm run hot`

will refresh the browser on changes in view & public folders

### CODE REVIEW

**Comment by amotenko** [comment]
@Yanipo5 is that used instead of nodemon?

**Comment by yaniv-peretz** [comment]
No.
This is for the "client-side" refresh only.
nmp run hot will refresh the browser (not the node server - which is done by nodemon)

**Comment by amotenko** [comment]
gotcha! thanks

**Comment by amotenko** [comment]
Also, can you add a few words on this to the dev readme file?
It will get lost if it's not there

**Comment by yaniv-peretz** [comment]
Sure I will...

**Comment by ghost** [comment]
I’ll be adding Webpack bundling as well, so better wait for that to update the docs

**Pull request merged**
