### PR TITLE
[WIP] .env support + remove passwords from codebase

### PR DESCRIPTION
**Pull request by amotenko**
**work in progress, don't merge**

### CODE REVIEW

**Comment by OriHoch** [comment]
if we are going to use .env file for configuration then we should remove the opsworks.js file completely and use the .env file directly

also, need to update the deployment scripts / procedures to use the .env file and have local developer environment have defaults

if you want I can do all of that..

**Comment by amotenko** [comment]
Sure, I think going with .env is the right choice for us.

**Comment by OriHoch** [comment]
cool, working on it

**Comment by OriHoch** [comment]
opened new PR, will continue the work there: #85

**Pull request closed without merging**
