### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by forye**

### CODE REVIEW

**Comment by forye** [comment]
I don't what is webpack and what is it used for... 

thanks a lot to  @netoneko

**Comment by ArtyomKa** [comment]
Heya.
Checked your PR. 
Looks like even with db line uncommented the web app still works with sqlite3 
There are a bunch of configurations that need to be taken care of (dev vs staging)

I have branch with working web<->mysql configuration working. I'm going to make a WIP pull request, so we can join forces.

**Comment by netoneko** [comment]
It will continue to work with sqlite3 unless you explicitly edit `opsworks.js`, where the configuration for db is stored.

**Comment by ripper234** [comment]
What does this PR do?

**Comment by ripper234** [comment]
@mtr574 @forye is still pull request active, or can we close it?
It has been `on:hold` for 1.5 months.

**Comment by OriHoch** [comment]
linked to this pull request from the docker issue: #24 

closing it because it is too old and requires to fix merge conflicts, also needs some documentation

feel free to re-open it if you want to continue as part of the docker issue #24

**Pull request closed without merging**
