### PR TITLE
[WIP] hotfix for v2.2.3 (production branch) - reset migrations and add mysql to travis

### PR DESCRIPTION
**Pull request by OriHoch**
**work in progress, don't merge**

- [ ] ~reset migrations~
  - handled in #338
- [x] add travis to mysql
  - done in roy-zahor/Spark#1
- [ ] ~update documentation - add clear instructions about how to use migrations~
  - this PR will be pointless if afterwards the same mistakes will be made again
  - will be handled in #350

### CODE REVIEW

**Comment by OriHoch** [comment]
@ArtyomKa feel free to continue working on it, I'll get back to it only tomorrow / later this week

**Comment by ArtyomKa** [comment]
@OriHoch IIUC, resetting the migrations will "force" them on the DB, right? what will happen with the existing data?

**Comment by OriHoch** [comment]
@ArtyomKa - my tought was to manually sync the DB to the migrations

knex uses a migrations table in DB - you can manually edit it to "fake" as if all migrations ran, then you manually make sure DB is in sync with migrations (e.g. that running migrations produces the same DB state as you have in production)

after that you need to start working with migrations properly - e.g. make new migrations each time, not edit existing migrations, test them properly etc..

**Comment by ArtyomKa** [comment]
@OriHoch 
Got the migrations and the tests passing. Do you want me to update this PR? How is it done? i just push to your branch or open a PR?

**Comment by OriHoch** [comment]
you should be able to push to my branch
or - push to a new branch and open a new pr, then close this pr

**Comment by ArtyomKa** [comment]
OK, I pushed to the branch on your fork. I removed all obsolete volunteers tables so there are less FK to worry about.
I think most of the problems that relations between tables where defined in the migrations and there are some type mismatches. like: `signed integer` references `unsigned integer`.
Sqllite does not realy support FK anyways, so it does not really care, but MySQL won't have it.. and migrations fail.
Also I'm not sure that defining many operations on different tables is such a good idea, cause there is no way to control in which order`Promise.all([])` executes them.

**Comment by ArtyomKa** [comment]
@OriHoch Now, that I have a better understanding about what your plan is, I'm not sure that my commit is good, as i removed some of the volunteers tables. So if they are present in the DB this commit should be reverted.

**Comment by roy-zahor** [comment]
Please take a look at https://github.com/Midburn/Spark/pull/338
I have done some work on the DB connectivity and made a lot of fixes for the migrations to allow them run on MySql. This might save you some time.

**Comment by OriHoch** [comment]
closing, see the updated description for details

**Pull request closed without merging**
